### ISSUE TITLE
Use DKMS and build into a debian package

### ISSUE THREAD

**Issue by paulbartell** [uw-biorobotics/usb-board-driver#1]
Build a debian/ubuntu package that uses DKMS to automatically recompile the kernel module when needed. Amend the init scripts to be correct as well. Example is at https://help.ubuntu.com/community/Kernel/DkmsDriverPackage

**Comment by awlewi** [comment]
Thanks Paul!

**Comment by paulbartell** [comment]
Almost a year after it was done.
